In [15]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob

df_auction = pd.read_csv('full_auction_cleaned.csv')
df_quote =  pd.read_csv('full_quote_cleaned.csv')

In [16]:
merged_inner = pd.merge(left=df_auction, right=df_quote, left_on='quote_id', right_on='quote_id')

In [17]:
merged_inner

,auction_brand,auction_date,auction_location,auction_model,auction_organizor,auction_price,auction_restauration_code,auction_sales_code,quote_id,auction_url,quote_max_price,quote_model,quote_year
0,ALFA ROMEO,20180118,PHOENIX,G 1 biplace course,RM Sotheby's,363570.0,REST,V,60,cote.encheres.php?idCote=60,-------,12/15/20 HP torpédo,1910
1,ALFA ROMEO,20060626,LONDRES,6 C 1750 Turismo cabriolet James Young (0412349),Christie's,51000.0,RAR,V,73,cote.encheres.php?idCote=73,90 000 €,6 C 1750 Turismo limousine,1929
2,ALFA ROMEO,20161125,MILAN,6 C 2500 Freccia d'Oro coach,RM Sotheby's,156800.0,RAR,V,90,cote.encheres.php?idCote=90,180 000 €,6 C 2500 Freccia d'Oro coach,1947
3,ALFA ROMEO,20140206,PARIS,6 C 2500 Freccia d'Oro coach tout alu,Bonhams,86250.0,REC,V,90,cote.encheres.php?idCote=90,180 000 €,6 C 2500 Freccia d'Oro coach,1947
4,ALFA ROMEO,20070219,PARIS,6 C 2500 Sport Freccia d'Oro coach (916218),Artcurial,53000.0,OR,V,90,cote.encheres.php?idCote=90,180 000 €,6 C 2500 Freccia d'Oro coach,1947
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9899,TRIUMPH,20090703,GOODWOOD,Dolomite 14 berline 4 cylindres,Bonhams,17050.0,REST,V,8237,cote.encheres.php?idCote=8237,13 000 €,Dolomite 14 berline 4 cylindres,1937
9900,TRIUMPH,20070227,LONDRES,Dolomite 14 berline RHD,Coys Auction,6050.0,OR+,V,8237,cote.encheres.php?idCote=8237,13 000 €,Dolomite 14 berline 4 cylindres,1937
9901,TRIUMPH,20170902,BEAULIEU,Gloria 6-cylindres Speed tourer,Bonhams,49960.0,REST,V,6731,cote.encheres.php?idCote=6731,13 000 €,Gloria Vitesse berline 6 cylindres,1935
9902,TRIUMPH,20060608,BROOKLANDS,Gloria Southern Cross roadster,BCA,24750.0,REST,V,6729,cote.encheres.php?idCote=6729,25 000 €,Gloria Southern Cross roadster 4 cylindres,1935
9903,TRIUMPH,20190320,DUXFORD,Gloria Monte Carlo tourer (moteur Ford A 3.3 l),H & H Classic Auctions,24680.0,TR,V,6728,cote.encheres.php?idCote=6728,18 500 €,Gloria Monte Carlo tourer 4 cylindres,1934

In [20]:
merged_inner.to_csv("merged_inner_quote_auction.csv", encoding='utf-8', index=False)